name: "Telegram Notification"

on:  
  workflow_run:
    workflows: [pages-build-deployment]
    types:
      - completed
  workflow_dispatch:

# Allow one concurrent deployment

jobs:
  telegram-notify:
    runs-on: ubuntu-latest
    steps:
      - name: send notification
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: markdown
          message: | 
            [[Video Link](undefinedtimelapse.mp4)] [[Page https://Philopho.github.io/alpha-data-beta-2024-06-00/]($url)]
